services:

  # ============================================
  # 🌐 API GATEWAY (Traefik + Gateway Service)
  # ============================================

  traefik:
    image: traefik:3
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"          # Dashboard activé en clair (⚠️ ne pas mettre en prod)
      - "--providers.docker=true"      # Auto-config à partir des labels Docker
      - "--entrypoints.web.address=:80" # Traefik écoute sur port 80
    ports:
      - "80:80"   # accès à l'API via http://localhost
      - "8080:8080" # Dashboard Traefik http://localhost:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    networks:
      - brokerx-network

  gateway-service:
      build: .
      container_name: gateway-service
      expose:
        - "8080"
      environment:
        GATEWAY_SECRET: ${GATEWAY_SECRET}
        JWT_SECRET: ${JWT_SECRET}
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gateway.rule=PathPrefix(`/`)"
        - "traefik.http.routers.gateway.entrypoints=web"
        - "traefik.http.services.gateway.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.ws-headers.headers.customrequestheaders.Connection=Upgrade"
        - "traefik.http.middlewares.ws-headers.headers.customrequestheaders.Upgrade=websocket"
        - "traefik.http.routers.gateway.middlewares=ws-headers"
        - "traefik.http.services.gateway.loadbalancer.passhostheader=true"
      restart: always
      networks:
        - brokerx-network

# ============================================
# 🌐 NETWORKS
# ============================================

networks:
  brokerx-network:
    external: true
    name: brokerx-network
