spring.application.name=Gateway_Service
server.port=8080

# Spring Cloud Gateway routes (local)

# Auth service route
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=0

# Wallet service route
spring.cloud.gateway.server.webflux.routes[2].id=wallet-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/wallet/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=0

# Market WebSocket route
spring.cloud.gateway.server.webflux.routes[1].id=market-service-ws
spring.cloud.gateway.server.webflux.routes[1].uri=ws://localhost:8083
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/ws/market/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=0

# Market REST route
spring.cloud.gateway.server.webflux.routes[3].id=market-service-rest
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/market/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=StripPrefix=0

# Order service route
spring.cloud.gateway.server.webflux.routes[4].id=order-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/order/**
spring.cloud.gateway.server.webflux.routes[4].filters[0]=StripPrefix=0


# CORS (relaxed for local dev)
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowCredentials=true

jwt.secret=${JWT_SECRET}
gateway.secret=${GATEWAY_SECRET}
