spring.application.name=Gateway_Service
server.port=8080

# Spring Cloud Gateway routes (local)
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=0

spring.cloud.gateway.server.webflux.routes[2].id=wallet-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/wallet/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=0

spring.cloud.gateway.server.webflux.routes[1].id=market-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/ws/market/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=0


# CORS (relaxed for local dev)
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowCredentials=true

jwt.secret=${JWT_SECRET}
gateway.secret=${GATEWAY_SECRET}
